### ISSUE TITLE
Validate handlers in dev mode

### ISSUE THREAD

**Issue by levithomason** [TechnologyAdvice/ta-react#14]
After #13 is merged and there is a pattern for dev mode validations, add basic validations for handlers.

- [ ] firs arg is a state object
- [ ] return value is a plain object
...

**Comment by dvdzkwsk** [comment]
FWIW the return value does not have to be a plain object, since the state of a reducer can be anything: a number, an array, an object, etc. Asserting that the handler exists and that its value is a function is a good conformance check that we should definitely sustain, but I think asserting the type of state (and consequently the return value of a handler) is best fit for userland where they can type their handlers/initial state as necessary.

👍 for assertion #1 and restricting these to development, though!

**Comment by levithomason** [comment]
Ah, totes.  The error I had here was actually not due to the return value as I had thought.  Being that the state can be anything, what are your thoughts on asserting the state param is not `undefined` and that the handler returns something other than `undefined`?
